name: Keep Streamlit App Awake

on:
  schedule:
    # Runs every 8 hours
    - cron: '0 */8 * * *'
  # Allows you to manually trigger the action from the GitHub UI to test it
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to the Streamlit app
        run: |
          curl -sIL https://omaralab-usage.streamlit.app/ | grep -E "^HTTP/"
